import sx.blah.discord.handle.obj.IChannel;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ray' at '1/15/18 1:54 PM' with Gradle 2.14.1
 *
 * @author ray, @date 1/15/18 1:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void sendMessage(IChannel channel, String message){
    	channel.sendMessage(message);
    }
}
